language: node_js
node_js:
  - "stable"

dist: focal

script:
  - npm install
  - npm run build

before_deploy:
  - rm -rf ./deploy
  - mkdir deploy
  - cp -r build/* deploy/
  - cd deploy
  - git init
  - git config user.name "Travis CI"
  - git config user.email "travis@users.noreply.github.com"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force "https://${GITHUB_TOKEN}@github.com/willowcampbell/COMP2156.git" main:gh-pages

deploy:
  skip_cleanup: true