language: node_js
node_js:
  - "stable"
dist: focal

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g yarn

script:
  #- yarn lint
  - yarn build
  - mv build/index.html build/404.html

before_deploy:
  - rm -rf deploy
  - mkdir deploy
  - rsync -av --exclude 'deploy' ./ deploy/
  - cd deploy
  - git init
  - git config user.name "Travis CI"
  - git config user.email "travis@users.noreply.github.com"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force "https://${GITHUB_TOKEN}@github.com/willowcampbell/COMP2156.git" main:gh-pages

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
  