language: node_js
node_js:
  - "stable"

dist: focal

script:
  - npm install

before_deploy:
  - gem install bundler:2.4.22

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  local_dir: build
  on:
    branch: main
