language: node_js
node_js:
  - "stable"
dist: focal

install:
  - npm install

script:
  - echo "No build step needed!"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main