language: node_js
node_js:
  - "stable"

dist: focal

script:
  - npm install
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  local_dir: build
  on:
    branch: main